apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: coaching-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: rahulpandit1234/coaching-portal-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@postgres:5432/coaching_db
            - name: SECRET_KEY
              value: mysecretkey
            - name: ALGORITHM
              value: HS256
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: "30"